config/routes.rb
Rails.application.routes.draw do

  get 'bases/new'

  root 'static_pages#top' 
  get '/signup', to: 'users#new'
  
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/edit-basic-info/:id', to: 'users#edit_basic_info', as: :basic_info
  patch 'update-basic-info', to: 'users#update_basic_info'
  get '/on_duty', to: 'users#on_duty'
  
  resources :bases
  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month' 
      patch 'attendances/update_one_month' 
    end
    resources :attendances, only: :update 
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :department, length: { in: 2..50 }, allow_blank: true
  validates :basic_time, presence: true
  validates :work_time, presence: true
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def User.search(search)
      return User.all unless search
      User.where(['name LIKE ?', "%#{search}%"])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy, :edit_basic_info, :update_basic_info, :index]
  before_action :set_one_month, only: :show 
  before_action :admin_correct_user, only: :show
 
  def index
    @users = User.paginate(page: params[:page], per_page: 20).search(params[:search])
  end
   
  def new
    @user = User.new
  end
  
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end
  
  def show
    @worked_sum = @attendances.where.not(started_at: nil).count
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
   if @user.update_attributes(user_params)
    flash[:success] = "ユーザー情報を更新しました。"
    redirect_to @user
   else
    render :edit      
   end
  end
  
  def edit_basic_info
  end
  
  def update_basic_info
   if @user.update_attributes(basic_info_params)
    flash[:success] = "基本情報を更新しました。"
    redirect_to @user   
   else
    render 'edit_basic_info'
   end
  end
  
  def on_duty
   @users = User.all.includes(:attendances)
  end
 
  
   private
  
   def user_params
    params.require(:user).permit(:name, :email, :department, :password, :password_confirmation)
   end
   
   def basic_info_params
    params.require(:user).permit(:basic_time, :work_time)
   end
   
end

app/helpers/users_helper.rb
module UsersHelper

  # 勤怠基本情報を指定のフォーマットで返します。  
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>
  
  <%= f.label :department, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '編集') %>
<h1>アカウント情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, "基本情報の更新") %>


<h1>基本情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: update_basic_info_path(params: {id: @user.id})) do |f| %>
      <%= render 'shared/error_messages', object: @user %>

      <%= f.label :basic_time %>
      <%= f.time_field :basic_time, class: 'form-control' %>

      <%= f.label :work_time %>
      <%= f.time_field :work_time, class: 'form-control' %>

      <%= f.submit "編集", class: 'btn btn-primary btn-block btn-edit' %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<% if request.fullpath == "/users?utf8=%E2%9C%93&search=" || request.fullpath == "/users" %>
 <h1>ユーザ一覧</h1>
<% else %>
 <h1>検索結果</h1>
<% end %>

<div class="col-md-10 col-md-offset-1">
    
  <div style="text-align: right">
  <p style="text-align: right">ユーザー名検索　　　　　</p>
   <%= form_tag(users_path,:method => 'get') do %>
    <%= text_field_tag :search %>
    <%= submit_tag '検索', :name => nil, class: "btn btn-xs btn-primary" %>
    </div>
   <% end %>
  <%= will_paginate %>
  <table class="table table-condensed table-hover" id="table-users">
    <thead>
      <tr>
        <th><%= User.human_attribute_name :name %></th>
      </tr>
    </thead>

    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %>
          ｜<%= link_to "基本情報編集", basic_info_path(user) %>
          <% if current_user.admin? && !current_user?(user) %>
            ｜<%= link_to "削除", user, method: :delete,
                data: { confirm: "削除してよろしいですか？" }%>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規登録') %>
<h1>アカウント作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
      <%= render 'form' %>
  </div>
</div>

app/views/users/on_duty.html.erb
<% provide(:title, "出勤中社員一覧") %>
<h1>出勤中社員一覧</h1>
  
<div>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th>社員番号</th>
        <th>名前</th>
      </tr>
    </thead>
   <tbody>
    <% @users.each do |user| %>
      <% user.attendances.each do |attendance| %>
       <% if Date.current == attendance.worked_on && attendance.started_at.present? && attendance.finished_at.nil? %>
     <tr>
      <td>
       <%=user.employee_number %>
      </td>
      <td>
       <%=user.name %>
      </td>
     </tr>
      <% end %>
    <% end %>
    <% end %>
    </tbody>
 </table>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div>
 <table class="table table-bordered table-condensed user-table">
   <tr>
     <td>
        <%= link_to "←",  user_path(date: @first_day.prev_month), class: "btn btn-xs btn-primary" %>
        &emsp;<%= l(@first_day, format: :middle) %> 時間管理表&emsp;
        <%= link_to "→", user_path(date: @first_day.next_month), class: "btn btn-xs btn-primary" %>
     </td>
     <td>指定勤務時間　<%= format_basic_info(@user.work_time) %></td>
     <td colspan="3"><%= format_basic_info(@user.basic_time) %>　基本時間</td>
     <td>初日：<%= l(@first_day, format: :short) %></td>
   </tr>
   <tr>
     <td>所属：<%= @user.department.present? ? @user.department : "未所属" %></td>
     <td>氏名　<%=@user.name%></td>
     <td>コード</td>
     <td></td>
     <td>出勤日数：<%= @worked_sum %>日</td>
     <td>締め：<%= l(@last_day, format: :short) %></td>
  </tr>   
 </table>
</div>
 <%= link_to "勤怠の編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-success" %>
<div>
 <table class="table table-bordered table-condensed table-hover" id="table-attendances">
   <thead>
      <tr> <!--rowspan:縦結合、colspan：横結合-->
        <th rowspan = "2">日付</th>
        <th rowspan = "2">曜日</th>
        <th colspan = "3">出社</th>
        <th colspan = "3">退社</th>
        <th rowspan = "2">在社時間</th>
        <th rowspan = "2">備考</th>
      </tr>
      <tr>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th></th>
      </tr>
   </thead>
   <tbody>
      <%  @attendances.each do |day| %>
        <tr>
          <td><%= l(day.worked_on, format: :short) %></td>
         <td>
          <% if day.worked_on.wday == 6 %>
           <font color="Blue">土</font>
          <% elsif day.worked_on.wday == 0 %>
           <font color="RED">日</font>
          <% else %>
          <%= $days_of_the_week[day.worked_on.wday] %>
          <% end %>
          </td>
          <td><%= l(day.started_at.floor_to(15.minutes), format: :only_time).to_i if day.started_at.present? %></td>
          <td><%= l(day.started_at.floor_to(15.minutes), format: :only_mi) if day.started_at.present? %></td>
          <td>  
          <% if day.worked_on == Date.current && day.started_at.nil? %>
           <%= link_to "出社", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
          <% end %>
          </td>
          <td><%= l(day.finished_at.floor_to(15.minutes), format: :only_time) if day.finished_at.present? %></td>
          <td><%= l(day.finished_at.floor_to(15.minutes), format: :only_mi) if day.finished_at.present? %></td>
          <td>
          <% if day.worked_on == Date.current && day.started_at.present? && day.finished_at.nil? %>
           <%= link_to "退社", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
          <% end %>
          </td>
          <td>
          <% if day.started_at.present? && day.finished_at.present? %>
           <%= str_times = working_times(day.started_at.floor_to(15.minutes), day.finished_at.floor_to(15.minutes)) %>
           <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
          <% end %>
          </td>
          <td><%= day.note %></td>
        </tr>
      <% end %>
    </tbody>
      <tfoot>
      <!--rowspan:縦結合、colspan：横結合-->
      <tr>
        <td colspan="2">累計日数</td>
        <td colspan="6">総合勤務時間</td>
        <td>累計在社時間</td>
        <td rowspan="2"></td>
      </tr>
      <tr>
        <td colspan="2"><%= @attendances.count %></td>
        <td colspan="6"><%= format_basic_info(@user.work_time).to_f * @worked_sum %></td>
        <td><%= format("%.2f", @total_working_times.to_f) %></td>
      </tr>
    </tfoot>
  </table>
</div>
 